version: '3.8'

services:
  tracer-study-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tracer-study-app:v10
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    command: sh -c "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs && chown -R www-data:www-data storage && php artisan migrate --force && php-fpm"
    volumes:
      - app-code-v10:/var/www
    networks:
      - tracer-study-network

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: tracer-study-web:v10
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - app-code-v10:/var/www
    depends_on:
      - tracer-study-app
    networks:
      - tracer-study-network

networks:
  tracer-study-network:
    driver: bridge

volumes:
  app-code-v10:
