version: '3.8'

services:
  tracer-study-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tracer-study-app
    container_name: tracer-study-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - app-code-v2:/var/www
    networks:
      - tracer-study-network

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: tracer-study-web
    container_name: tracer-study-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app-code-v2:/var/www
    depends_on:
      - tracer-study-app
    networks:
      - tracer-study-network

networks:
  tracer-study-network:
    driver: bridge

volumes:
  app-code-v2:
